class Constants:
    LOL2REG={
        'BR1': 'br',
        'EUN1': 'eu',
        'EUW1': 'eu',
        'JP1': 'ap',
        'KR': 'kr',
        'LA1': 'latam',
        'LA2': 'latam',
        'NA1': 'na',
        'OC1': 'ap',
        'PBE1': 'na',
        'RU': 'eu',
        'TR1': 'eu'
    }

    #please contact me if u found a mistake
    COU2REG={
        "BD": "AP",
        "BE": "EU",
        "BF": "EU",
        "BG": "EU",
        "BA": "EU",
        "BB": "NA",
        "WF": "AP",
        "BL": "NA",
        "BM": "NA",
        "BN": "AP",
        "BO": "LATAM",
        "BH": "AP",
        "BI": "EU",
        "BJ": "EU",
        "BT": "AP",
        "JM": "NA",
        "BV": "AN",
        "BW": "EU",
        "WS": "AP",
        "BQ": "NA",
        "BR": "BR",
        "BS": "NA",
        "JE": "EU",
        "BY": "EU",
        "BZ": "NA",
        "RU": "EU",
        "RW": "EU",
        "RS": "EU",
        "TL": "AP",
        "RE": "EU",
        "TM": "AP",
        "TJ": "AP",
        "RO": "EU",
        "TK": "AP",
        "GW": "EU",
        "GU": "AP",
        "GT": "NA",
        "GS": "AN",
        "GR": "EU",
        "GQ": "EU",
        "GP": "NA",
        "JP": "AP",
        "GY": "LATAM",
        "GG": "EU",
        "GF": "LATAM",
        "GE": "AP",
        "GD": "NA",
        "GB": "EU",
        "GA": "EU",
        "SV": "NA",
        "GN": "EU",
        "GM": "EU",
        "GL": "NA",
        "GI": "EU",
        "GH": "EU",
        "OM": "AP",
        "TN": "EU",
        "JO": "AP",
        "HR": "EU",
        "HT": "NA",
        "HU": "EU",
        "HK": "AP",
        "HN": "NA",
        "HM": "AN",
        "VE": "LATAM",
        "PR": "NA",
        "PS": "AP",
        "PW": "AP",
        "PT": "EU",
        "SJ": "EU",
        "PY": "LATAM",
        "IQ": "AP",
        "PA": "NA",
        "PF": "AP",
        "PG": "AP",
        "PE": "LATAM",
        "PK": "AP",
        "PH": "AP",
        "PN": "AP",
        "PL": "EU",
        "PM": "NA",
        "ZM": "EU",
        "EH": "EU",
        "EE": "EU",
        "EG": "EU",
        "ZA": "EU",
        "EC": "LATAM",
        "IT": "EU",
        "VN": "AP",
        "SB": "AP",
        "ET": "EU",
        "SO": "EU",
        "ZW": "EU",
        "ES": "EU",
        "ER": "EU",
        "ME": "EU",
        "MD": "EU",
        "MG": "EU",
        "MF": "NA",
        "MA": "EU",
        "MC": "EU",
        "UZ": "AP",
        "MM": "AP",
        "ML": "EU",
        "MO": "AP",
        "MN": "AP",
        "MH": "AP",
        "MK": "EU",
        "MU": "EU",
        "MT": "EU",
        "MW": "EU",
        "MV": "AP",
        "MQ": "NA",
        "MP": "AP",
        "MS": "NA",
        "MR": "EU",
        "IM": "EU",
        "UG": "EU",
        "TZ": "EU",
        "MY": "AP",
        "MX": "NA",
        "IL": "AP",
        "FR": "EU",
        "IO": "AP",
        "SH": "EU",
        "FI": "EU",
        "FJ": "AP",
        "FK": "LATAM",
        "FM": "AP",
        "FO": "EU",
        "NI": "NA",
        "NL": "EU",
        "NO": "EU",
        "NA": "EU",
        "VU": "AP",
        "NC": "AP",
        "NE": "EU",
        "NF": "AP",
        "NG": "EU",
        "NZ": "AP",
        "NP": "AP",
        "NR": "AP",
        "NU": "AP",
        "CK": "AP",
        "XK": "EU",
        "CI": "EU",
        "CH": "EU",
        "CO": "LATAM",
        "CN": "AP",
        "CM": "EU",
        "CL": "LATAM",
        "CC": "AP",
        "CA": "NA",
        "CG": "EU",
        "CF": "EU",
        "CD": "EU",
        "CZ": "EU",
        "CY": "EU",
        "CX": "AP",
        "CR": "NA",
        "CW": "NA",
        "CV": "EU",
        "CU": "NA",
        "SZ": "EU",
        "SY": "AP",
        "SX": "NA",
        "KG": "AP",
        "KE": "EU",
        "SS": "EU",
        "SR": "LATAM",
        "KI": "AP",
        "KH": "AP",
        "KN": "NA",
        "KM": "EU",
        "ST": "EU",
        "SK": "EU",
        "KR": "KR",
        "SI": "EU",
        "KP": "AP",
        "KW": "AP",
        "SN": "EU",
        "SM": "EU",
        "SL": "EU",
        "SC": "EU",
        "KZ": "AP",
        "KY": "NA",
        "SG": "AP",
        "SE": "EU",
        "SD": "EU",
        "DO": "NA",
        "DM": "NA",
        "DJ": "EU",
        "DK": "EU",
        "VG": "NA",
        "DE": "EU",
        "YE": "AP",
        "DZ": "EU",
        "US": "NA",
        "UY": "LATAM",
        "YT": "EU",
        "UM": "AP",
        "LB": "AP",
        "LC": "NA",
        "LA": "AP",
        "TV": "AP",
        "TW": "AP",
        "TT": "NA",
        "TR": "EU",
        "LK": "AP",
        "LI": "EU",
        "LV": "EU",
        "TO": "AP",
        "LT": "EU",
        "LU": "EU",
        "LR": "EU",
        "LS": "EU",
        "TH": "AP",
        "TF": "AN",
        "TG": "EU",
        "TD": "EU",
        "TC": "NA",
        "LY": "EU",
        "VA": "EU",
        "VC": "NA",
        "AE": "AP",
        "AD": "EU",
        "AG": "NA",
        "AI": "NA",
        "VI": "NA",
        "IS": "EU",
        "IR": "AP",
        "AM": "AP",
        "AL": "EU",
        "AO": "EU",
        "AQ": "AN",
        "AP": "AP",
        "AR": "LATAM",
        "AU": "AP",
        "AT": "EU",
        "AW": "NA",
        "IN": "AP",
        "AX": "EU",
        "AZ": "AP",
        "IE": "EU",
        "ID": "AP",
        "UA": "EU",
        "QA": "AP",
        "MZ": "EU"
    }

    A2TOA3={
        'AFG':'AF',
        'ALA':'AX',
        'ALB':'AL',
        'DZA':'DZ',
        'ASM':'AS',
        'AND':'AD',
        'AGO':'AO',
        'AIA':'AI',
        'ATA':'AQ',
        'ATG':'AG',
        'ARG':'AR',
        'ARM':'AM',
        'ABW':'AW',
        'AUS':'AU',
        'AUT':'AT',
        'AZE':'AZ',
        'BHS':'BS',
        'BHR':'BH',
        'BGD':'BD',
        'BRB':'BB',
        'BLR':'BY',
        'BEL':'BE',
        'BLZ':'BZ',
        'BEN':'BJ',
        'BMU':'BM',
        'BTN':'BT',
        'BOL':'BO',
        'BES':'BQ',
        'BIH':'BA',
        'BWA':'BW',
        'BVT':'BV',
        'BRA':'BR',
        'IOT':'IO',
        'BRN':'BN',
        'BGR':'BG',
        'BFA':'BF',
        'BDI':'BI',
        'CPV':'CV',
        'KHM':'KH',
        'CMR':'CM',
        'CAN':'CA',
        'CYM':'KY',
        'CAF':'CF',
        'TCD':'TD',
        'CHL':'CL',
        'CHN':'CN',
        'CXR':'CX',
        'CCK':'CC',
        'COL':'CO',
        'COM':'KM',
        'COG':'CG',
        'COD':'CD',
        'COK':'CK',
        'CRI':'CR',
        'CIV':'CI',
        'HRV':'HR',
        'CUB':'CU',
        'CUW':'CW',
        'CYP':'CY',
        'CZE':'CZ',
        'DNK':'DK',
        'DJI':'DJ',
        'DMA':'DM',
        'DOM':'DO',
        'ECU':'EC',
        'EGY':'EG',
        'SLV':'SV',
        'GNQ':'GQ',
        'ERI':'ER',
        'EST':'EE',
        'SWZ':'SZ',
        'ETH':'ET',
        'FLK':'FK',
        'FRO':'FO',
        'FJI':'FJ',
        'FIN':'FI',
        'FRA':'FR',
        'GUF':'GF',
        'PYF':'PF',
        'ATF':'TF',
        'GAB':'GA',
        'GMB':'GM',
        'GEO':'GE',
        'DEU':'DE',
        'GHA':'GH',
        'GIB':'GI',
        'GRC':'GR',
        'GRL':'GL',
        'GRD':'GD',
        'GLP':'GP',
        'GUM':'GU',
        'GTM':'GT',
        'GGY':'GG',
        'GIN':'GN',
        'GNB':'GW',
        'GUY':'GY',
        'HTI':'HT',
        'HMD':'HM',
        'VAT':'VA',
        'HND':'HN',
        'HKG':'HK',
        'HUN':'HU',
        'ISL':'IS',
        'IND':'IN',
        'IDN':'ID',
        'IRN':'IR',
        'IRQ':'IQ',
        'IRL':'IE',
        'IMN':'IM',
        'ISR':'IL',
        'ITA':'IT',
        'JAM':'JM',
        'JPN':'JP',
        'JEY':'JE',
        'JOR':'JO',
        'KAZ':'KZ',
        'KEN':'KE',
        'KIR':'KI',
        'PRK':'KP',
        'KOR':'KR',
        'KWT':'KW',
        'KGZ':'KG',
        'LAO':'LA',
        'LVA':'LV',
        'LBN':'LB',
        'LSO':'LS',
        'LBR':'LR',
        'LBY':'LY',
        'LIE':'LI',
        'LTU':'LT',
        'LUX':'LU',
        'MAC':'MO',
        'MDG':'MG',
        'MWI':'MW',
        'MYS':'MY',
        'MDV':'MV',
        'MLI':'ML',
        'MLT':'MT',
        'MHL':'MH',
        'MTQ':'MQ',
        'MRT':'MR',
        'MUS':'MU',
        'MYT':'YT',
        'MEX':'MX',
        'FSM':'FM',
        'MDA':'MD',
        'MCO':'MC',
        'MNG':'MN',
        'MNE':'ME',
        'MSR':'MS',
        'MAR':'MA',
        'MOZ':'MZ',
        'MMR':'MM',
        'NAM':'NA',
        'NRU':'NR',
        'NPL':'NP',
        'NLD':'NL',
        'NCL':'NC',
        'NZL':'NZ',
        'NIC':'NI',
        'NER':'NE',
        'NGA':'NG',
        'NIU':'NU',
        'NFK':'NF',
        'MKD':'MK',
        'MNP':'MP',
        'NOR':'NO',
        'OMN':'OM',
        'PAK':'PK',
        'PLW':'PW',
        'PSE':'PS',
        'PAN':'PA',
        'PNG':'PG',
        'PRY':'PY',
        'PER':'PE',
        'PHL':'PH',
        'PCN':'PN',
        'POL':'PL',
        'PRT':'PT',
        'PRI':'PR',
        'QAT':'QA',
        'REU':'RE',
        'ROU':'RO',
        'RUS':'RU',
        'RWA':'RW',
        'BLM':'BL',
        'SHN':'SH',
        'KNA':'KN',
        'LCA':'LC',
        'MAF':'MF',
        'SPM':'PM',
        'VCT':'VC',
        'WSM':'WS',
        'SMR':'SM',
        'STP':'ST',
        'SAU':'SA',
        'SEN':'SN',
        'SRB':'RS',
        'SYC':'SC',
        'SLE':'SL',
        'SGP':'SG',
        'SXM':'SX',
        'SVK':'SK',
        'SVN':'SI',
        'SLB':'SB',
        'SOM':'SO',
        'ZAF':'ZA',
        'SGS':'GS',
        'SSD':'SS',
        'ESP':'ES',
        'LKA':'LK',
        'SDN':'SD',
        'SUR':'SR',
        'SJM':'SJ',
        'SWE':'SE',
        'CHE':'CH',
        'SYR':'SY',
        'TWN':'TW',
        'TJK':'TJ',
        'TZA':'TZ',
        'THA':'TH',
        'TLS':'TL',
        'TGO':'TG',
        'TKL':'TK',
        'TON':'TO',
        'TTO':'TT',
        'TUN':'TN',
        'TUR':'TR',
        'TKM':'TM',
        'TCA':'TC',
        'TUV':'TV',
        'UGA':'UG',
        'UKR':'UA',
        'ARE':'AE',
        'GBR':'GB',
        'USA':'US',
        'UMI':'UM',
        'URY':'UY',
        'UZB':'UZ',
        'VUT':'VU',
        'VEN':'VE',
        'VNM':'VN',
        'VGB':'VG',
        'VIR':'VI',
        'WLF':'WF',
        'ESH':'EH',
        'YEM':'YE',
        'ZMB':'ZM',
        'ZWE':'ZW',
    }

    skinprice={
        'Luxe Ghost':875,
        'Luxe Ghost':875,
        'Luxe Spectre':875,
        'Luxe Judge':875,
        'Luxe Vandal':875,
        'Luxe Operator':875,
        'Luxe Knife':1750,
        'Aristocrat Sheriff':1275,
        'Aristocrat Stinger':1275,
        'Aristocrat Bulldog':1275,
        'Aristocrat Vandal':1275,
        'Aristocrat Ares':1275,
        'Galleria Classic':875,
        'Galleria Bucky':875,
        'Galleria Guardian':875,
        'Galleria Phantom':875,
        'Galleria Marshal':875,
        'Rush Frenzy':875,
        'Rush Judge':875,
        'Rush Bulldog':875,
        'Rush Phantom':875,
        'Rush Ares':875,
        'Sakura Classic':1275,
        'Sakura Sheriff':1275,
        'Sakura Stinger':1275,
        'Sakura Vandal':1275,
        'Sakura Ares':1275,
        'Convex Sheriff':875,
        'Convex Spectre':875,
        'Convex Judge':875,
        'Convex Bulldog':875,
        'Convex Operator':875,
        'Avalanche Classic':1275,
        'Avalanche Spectre':1275,
        'Avalanche Phantom':1275,
        'Avalanche Vandal':1275,
        'Avalanche Marshal':1275,
        'Prime Classic':1775,
        'Prime Spectre':1775,
        'Prime Guardian':1775,
        'Prime Vandal':1775,
        'Prime Axe':3550,
        'Sovereign Ghost':1775,
        'Sovereign Stinger':1775,
        'Sovereign Guardian':1775,
        'Sovereign Marshal':1775,
        'Sovereign Sword':3550,
        'Prism Ghost':1275,
        'Prism Spectre':1275,
        'Prism Phantom':1275,
        'Prism Operator':1275,
        'Prism Ares':1275,
        'Prism Knife':2550,
        'Elderflame Frenzy':2475,
        'Elderflame Judge':2475,
        'Elderflame Vandal':2475,
        'Elderflame Operator':2475,
        'Elderflame Dagger':4950,
        'Oni Shorty':1775,
        'Oni Bucky':1775,
        'Oni Guardian':1775,
        'Oni Phantom':1775,
        'Oni Claw':3550,
        'Glitchpop Frenzy':2175,
        'Glitchpop Judge':2175,
        'Glitchpop Bulldog':2175,
        'Glitchpop Odin':2175,
        'Glitchpop Dagger':4350,
        'Nebula Sheriff':1775,
        'Nebula Guardian':1775,
        'Nebula Phantom':1775,
        'Nebula Ares':1775,
        'Nebula Knife':3550,
        'Spline Classic':1775,
        'Spline Spectre':1775,
        'Spline Phantom':1775,
        'Spline Operator':1775,
        'Spline Dagger':3550,
        'Ego Ghost':1775,
        'Ego Stinger':1775,
        'Ego Guardian':1775,
        'Ego Vandal':1775,
        'Ego Knife':3550,
        'Smite Classic':875,
        'Smite Judge':875,
        'Smite Phantom':875,
        'Smite Odin':875,
        'Smite Knife':1750,
        'Gravitational Uranium Neuroblaster Classic':1775,
        'Gravitational Uranium Neuroblaster Spectre':1775,
        'Gravitational Uranium Neuroblaster Bucky':1775,
        'Gravitational Uranium Neuroblaster Operator':1775,
        'Gravitational Uranium Neuroblaster Baton':3550,
        'Singularity Sheriff':2175,
        'Singularity Spectre':2175,
        'Singularity Phantom':2175,
        'Singularity Ares':2175,
        'Singularity Knife':4350,
        'Reaver Sheriff':1775,
        'Reaver Guardian':1775,
        'Reaver Vandal':1775,
        'Reaver Operator':1775,
        'Reaver Knife':3550,
        'Ion Sheriff':1775,
        'Ion Bucky':1775,
        'Ion Phantom':1775,
        'Ion Operator':1775,
        'Ion Energy Sword':3550,
        'Wasteland Shorty':1275,
        'Wasteland Sheriff':1275,
        'Wasteland Spectre':1275,
        'Wasteland Vandal':1275,
        'Wasteland Marshal':1275,
        'Sensation Frenzy':875,
        'Sensation Stinger':875,
        'Sensation Judge':875,
        'Sensation Vandal':875,
        'Sensation Odin':875,
        'Winterwunderland Ghost':1275,
        'Winterwunderland Phantom':1275,
        'Winterwunderland Vandal':1275,
        'Winterwunderland Marshal':1275,
        'Winterwunderland Candy Cane':2550,
        'BlastX Frenzy':2175,
        'BlastX Spectre':2175,
        'BlastX Phantom':2175,
        'BlastX Odin':2175,
        'BlastX Polymer Knifetech Coated Knife':4350,
        'Prism II Shorty':875,
        'Prism II Sheriff':875,
        'Prism II Stinger':875,
        'Prism II Bucky':875,
        'Prism II Vandal':875,
        'Horizon Frenzy':1275,
        'Horizon Spectre':1275,
        'Horizon Bucky':1275,
        'Horizon Bulldog':1275,
        'Horizon Vandal':1275,
        'Glitchpop Classic':2175,
        'Glitchpop Phantom':2175,
        'Glitchpop Vandal':2175,
        'Glitchpop Operator':2175,
        'Glitchpop Axe':4350,
        'Celestial Frenzy':1775,
        'Celestial Judge':1775,
        'Celestial Phantom':1775,
        'Celestial Ares':1775,
        'Celestial Fan':3550,
        'VALORANT Go! Vol. 1 Ghost':1775,
        'VALORANT Go! Vol. 1 Spectre':1775,
        'VALORANT Go! Vol. 1 Guardian':1775,
        'VALORANT Go! Vol. 1 Phantom':1775,
        'VALORANT Go! Vol. 1 Knife':3550,
        'Prime 2.0 Frenzy':1775,
        'Prime 2.0 Bucky':1775,
        'Prime 2.0 Phantom':1775,
        'Prime 2.0 Odin':1775,
        'Prime 2.0 Karambit':3550,
        'Infantry Ghost':875,
        'Infantry Spectre':875,
        'Infantry Guardian':875,
        'Infantry Operator':875,
        'Infantry Ares':875,
        'Magepunk Ghost':1775,
        'Magepunk Spectre':1775,
        'Magepunk Bucky':1775,
        'Magepunk Marshal':1775,
        'Magepunk Electroblade':3550,
        'Silvanus Sheriff':1275,
        'Silvanus Stinger':1275,
        'Silvanus Phantom':1275,
        'Silvanus Vandal':1275,
        'Silvanus Operator':1275,
        'Forsaken Classic':1775,
        'Forsaken Spectre':1775,
        'Forsaken Vandal':1775,
        'Forsaken Operator':1775,
        'Forsaken Ritual Blade':3550,
        'Minima Sheriff':1275,
        'Minima Spectre':1275,
        'Minima Phantom':1275,
        'Minima Operator':1275,
        'Minima Ares':1275,
        'Tethered Realms Ghost':1775,
        'Tethered Realms Guardian':1775,
        'Tethered Realms Vandal':1775,
        'Tethered Realms Operator':1775,
        'Tethered Realms Prosperity':3550,
        'Origin Frenzy':1775,
        'Origin Bucky':1775,
        'Origin Vandal':1775,
        'Origin Operator':1775,
        'Origin Crescent Blade':3550,
        'Ruination Ghost':2175,
        'Ruination Spectre':2175,
        'Ruination Guardian':2175,
        'Ruination Phantom':2175,
        'Ruination Broken Blade Of The Ruined King':4350,
        'Sentinels of Light Sheriff':2175,
        'Sentinels of Light Vandal':2175,
        'Sentinels of Light Operator':2175,
        'Sentinels of Light Ares':2175,
        'Sentinels of Light Relic of the Sentinel':4350,
        'Recon Ghost':1775,
        'Recon Spectre':1775,
        'Recon Guardian':1775,
        'Recon Phantom':1775,
        'Recon Balisong':3550,
        'Spectrum Classic':2675,
        'Spectrum Bulldog':2675,
        'Spectrum Guardian':2675,
        'Spectrum Phantom':2675,
        'Spectrum Waveform':5350,
        'VALORANT Go! Vol. 2 Classic':1775,
        'VALORANT Go! Vol. 2 Vandal':1775,
        'VALORANT Go! Vol. 2 Operator':1775,
        'VALORANT Go! Vol. 2 Ares':1775,
        'VALORANT Go! Vol. 2 Yoru\'s Stylish Butterfly Comb':3550,
        'RGX 11z Pro Frenzy':2175,
        'RGX 11z Pro Stinger':2175,
        'RGX 11z Pro Guardian':2175,
        'RGX 11z Pro Vandal':2175,
        'RGX 11z Pro Blade':4350,
        'Nunca Olvidados Frenzy':1275,
        'Nunca Olvidados Bulldog':1275,
        'Nunca Olvidados Vandal':1275,
        'Nunca Olvidados Ares':1275,
        'Nunca Olvidados Catrina':2550,
        'Radiant Crisis 001 Classic':1775,
        'Radiant Crisis 001 Spectre':1775,
        'Radiant Crisis 001 Bucky':1775,
        'Radiant Crisis 001 Phantom':1775,
        'Radiant Crisis 001 Baseball Bat':3550,
        'Magepunk Sheriff':1775,
        'Magepunk Guardian':1775,
        'Magepunk Operator':1775,
        'Magepunk Ares':1775,
        'Magepunk Shock Gauntlet':3550,
        'Snowfall Classic':1275,
        'Snowfall Judge':1275,
        'Snowfall Phantom':1275,
        'Snowfall Ares':1275,
        'Snowfall Wand':2550,
        'Protocol 781-A Sheriff':2475,
        'Protocol 781-A Spectre':2475,
        'Protocol 781-A Bulldog':2475,
        'Protocol 781-A Phantom':2475,
        'Protocol 781-A Personal Administrative Melee Unit':4950,
        'Tigris Shorty':1275,
        'Tigris Spectre':1275,
        'Tigris Phantom':1275,
        'Tigris Operator':1275,
        'Tigris Hu Else':2550,
        'Undercity Classic':1775,
        'Undercity Judge':1775,
        'Undercity Bulldog':1775,
        'Undercity Phantom':1775,
        'Undercity Hack':3550,
        'Gaia\'s Vengeance Ghost':1775,
        'Gaia\'s Vengeance Guardian':1775,
        'Gaia\'s Vengeance Vandal':1775,
        'Gaia\'s Vengeance Marshal':1775,
        'Gaia\'s Vengeance Gaia\'s Wrath':3550,
        'Team Ace Frenzy':1275,
        'Team Ace Judge':1275,
        'Team Ace Phantom':1275,
        'Team Ace Vandal':1275,
        'Team Ace Operator':1275,
        'Endeavour Ghost':875,
        'Endeavour Bulldog':875,
        'Endeavour Vandal':875,
        'Endeavour Operator':875,
        'Endeavour Ares':875,
        'Doodle Buds Shorty':1775,
        'Doodle Buds Stinger':1775,
        'Doodle Buds Phantom':1775,
        'Doodle Buds Marshal':1775,
        'Doodle Buds Ares':1775,
        'RGX 11z Pro Classic':2175,
        'RGX 11z Pro Spectre':2175,
        'RGX 11z Pro Phantom':2175,
        'RGX 11z Pro Operator':2175,
        'RGX 11z Pro Firefly':4350,
        'Titanmail Frenzy':1275,
        'Titanmail Bucky':1275,
        'Titanmail Vandal':1275,
        'Titanmail Ares':1275,
        'Titanmail Mace':2550,
        'Neptune Shorty':1775,
        'Neptune Spectre':1775,
        'Neptune Guardian':1775,
        'Neptune Vandal':1775,
        'Neptune Anchor':3550,
        'Xenohunter Frenzy':1775,
        'Xenohunter Bucky':1775,
        'Xenohunter Phantom':1775,
        'Xenohunter Odin':1775,
        'Xenohunter Knife':3550,
        'Prelude to Chaos Shorty':2175,
        'Prelude to Chaos Stinger':2175,
        'Prelude to Chaos Vandal':2175,
        'Prelude to Chaos Operator':2175,
        'Prelude to Chaos Blade of Chaos':4350,
        'Sarmad Frenzy':1275,
        'Sarmad Spectre':1275,
        'Sarmad Phantom':1275,
        'Sarmad Vandal':1275,
        'Sarmad Blade of Serket':2550,
        'Reaver Ghost':1775,
        'Reaver Spectre':1775,
        'Reaver Phantom':1775,
        'Reaver Odin':1775,
        'Reaver Karambit':4350,
        'Kohaku & Matsuba Classic':1275,
        'Kohaku & Matsuba Judge':1275,
        'Kohaku & Matsuba Phantom':1275,
        'Kohaku & Matsuba Operator':1275,
        'Kohaku & Matsuba Equilibrium':2550,
        'ChronoVoid Sheriff':2175,
        'ChronoVoid Judge':2175,
        'ChronoVoid Phantom':2175,
        'ChronoVoid Vandal':2175,
        'ChronoVoid Terminus A Quo':4350,
    }

    USER_AGENT = {"User-Agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36"}
    CLIENTPLATFORM = 'ew0KCSJwbGF0Zm9ybVR5cGUiOiAiUEMiLA0KCSJwbGF0Zm9ybU9TIjogIldpbmRvd3MiLA0KCSJwbGF0\
Zm9ybU9TVmVyc2lvbiI6ICIxMC4wLjE5MDQyLjEuMjU2LjY0Yml0IiwNCgkicGxhdGZvcm1DaGlwc2V0IjogIlVua25vd24iDQp9'
    
    CIPHERS = [
	'ECDHE-ECDSA-AES128-GCM-SHA256',
	'ECDHE-ECDSA-CHACHA20-POLY1305',
	'ECDHE-RSA-AES128-GCM-SHA256',
	'ECDHE-RSA-CHACHA20-POLY1305',
	'ECDHE+AES128',
	'RSA+AES128',
	'ECDHE+AES256',
	'RSA+AES256',
	'ECDHE+3DES',
	'RSA+3DES'
    ]
    AUTH_URL = "https://auth.riotgames.com/api/v1/authorization"
    REGION_URL = 'https://riot-geo.pas.si.riotgames.com/pas/v1/product/valorant'
    VERIFED_URL = "https://email-verification.riotgames.com/api/v1/account/status"
    ENTITLEMENT_URL = 'https://entitlements.auth.riotgames.com/api/token/v1'
    USERINFO_URL = "https://auth.riotgames.com/userinfo"
    RIOTCLIENT = ''
    ICONURL = 'https://media.valorant-api.com/weaponskins/{}/displayicon.png'
    ICONURL2 = 'https://media.valorant-api.com/weaponskinlevels/{}/displayicon.png'